-- AlterTable: add ACCOUNT_DEACTIVATED to EmailTemplateType enum
ALTER TABLE `EmailTemplate` MODIFY COLUMN `type` ENUM('WELCOME', 'PAYMENT_CONFIRMATION', 'PAYMENT_REMINDER', 'PASSWORD_RESET', 'EMAIL_CHANGE', 'ACCOUNT_DEACTIVATED') NOT NULL;
